name: LINT - BUILD - TEST
on: [push]
jobs:
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2
      - run: echo "Install Dependencies"
      - name: Install Dependencies
        run: npm install

      - run: echo "Starting Code linting"
      - name: Code Linting
        run: npm run lint
      - run: echo "Starting Code finish"

