name: pre-build
on: [push]
jobs:
  pre-build:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.5
          cache: 'npm'
      - run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run Build
        run: npm run build
